/*
Module/Class Name: BookingCreateHandler.java
Date of Code: 02/29/26
Programmer: Esmeralda Munoz
Brief Description: The BookingCreateHandler.java class takes the 
cart items and creates a booking file.

Important Functions:

handle(HttpExchange exchange)
Input: HTTP request
Output: Response text

Purpose: Takes the cart items, creates a 
booking, writes the booking to the bookings file, and clears the cart.

Important Data Structures:
- Cart items from cart.txt file
- Booking records written into bookings.txt file
- Booking objects

Algorithm/Design Used: Booking IDs are generated by taking the number of 
bookings in the system and incrementing that number by one to create 
the next booking ID.
*/

import com.sun.net.httpserver.*;
import java.io.*;
import java.nio.file.*;
import java.util.*;

public class BookingCreateHandler implements HttpHandler {
    public void handle(HttpExchange exchange) throws IOException {
        File cartFile = new File("cart.txt");
        File bookingsFile = new File("bookings.txt");
        if (!cartFile.exists()) {
            cartFile.createNewFile();
        }
        if (!bookingsFile.exists()) {
            bookingsFile.createNewFile();
        }

        List<String> cartLines = Files.readAllLines(Paths.get("cart.txt"));
        if (cartLines.isEmpty()) {
            send(exchange, "Cart is empty");
            return;
        }

        List<String> bookingLines = Files.readAllLines(Paths.get("bookings.txt"));
        int nextId = bookingLines.size() + 1;

        FileWriter fw = new FileWriter("bookings.txt", true);
        for (String line : cartLines) {
            String[] parts = line.split("\\|");
            if (parts.length == 5) {
                Booking booking = new Booking(
                    nextId,
                    Integer.parseInt(parts[0]),
                    parts[1],
                    parts[2],
                    Double.parseDouble(parts[3]),
                    Integer.parseInt(parts[4]),
                    "BOOKED"
                );
                fw.write(booking.toLine() + "\n");
                nextId++;
            }
        }
        fw.close();

        Files.write(Paths.get("cart.txt"), new ArrayList<String>());
        send(exchange, "Booking created");
    }

    private void send(HttpExchange exchange, String response) throws IOException {
        exchange.getResponseHeaders().add("Access-Control-Allow-Origin", "*");
        exchange.getResponseHeaders().add("Content-Type", "text/plain");
        exchange.sendResponseHeaders(200, response.length());
        OutputStream os = exchange.getResponseBody();
        os.write(response.getBytes());
        os.close();
    }
}